# Generated by Django 5.0.6 on 2024-07-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usersettings_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='send_to_email',
            field=models.BooleanField(default=True),
        ),
    ]
