# Generated by Django 5.0.6 on 2024-07-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usersettings_send_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='thread_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
