# Generated by Django 5.0.6 on 2024-07-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reminder_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='send_to_discord',
            field=models.BooleanField(default=False),
        ),
    ]
