# Generated by Django 5.0.6 on 2024-07-02 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usersettings_discord_id_usersettings_send_to_discord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_text',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='thread_id',
        ),
        migrations.AddField(
            model_name='reminder',
            name='discord_thread_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='email_thread_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='message_thread_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
