# Generated by Django 5.0.6 on 2024-07-02 08:42

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_reminder_created_at_remove_reminder_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 8, 42, 17, 791502, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_text',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
